version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t auto:latest .
      - docker tag auto:latest 548020302753.dkr.ecr.us-east-1.amazonaws.com/auto:latest
  post_build:
    commands:
      - docker push 548020302753.dkr.ecr.us-east-1.amazonaws.com/auto:latest
      - printf '[{"name":<task03>,"imageUri":"%s"}]' 548020302753.dkr.ecr.us-east-1.amazonaws.com/auto:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
